version: '3.8'
services:
  api:
    build: .
    container_name: lead-management-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
